// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv"
import "dotenv/config"
import { defineConfig } from "prisma/config"

config({
  path: `.env.${process.env.NODE_ENV === "production" ? "production" : "development"}`,
})

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
})
